---
name: Sample
pack: mail_command
description: メールを受信したらその本文に記述されているコマンドを対象サーバで実行し、結果を送信者にメールする
enabled: true
trigger:
    type: email.imap.message
criteria:
    trigger.subject:
        type: "regex"
        pattern: "コマンド実行@\\w+"
action:
    ref: mail_command.mail_command
    parameters:
        node: {{ trigger.subject|trim|replace('コマンド実行\@', '') }}
        command_text: {{ trigger.body }}
        reply_to: {{ trigger.from }}
